services:
  hello-go:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hello-go
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/"]
      interval: 10s
      timeout: 3s
      retries: 5
